import { PrismaClient } from '@prisma/client';
import { hashSync } from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // Create admin user
  await prisma.adminUser.upsert({
    where: { username: 'admin' },
    update: {},
    create: {
      username: 'admin',
      passwordHash: hashSync('admin123', 12),
      name: 'Admin',
    },
  });

  // Create test modes
  await prisma.testMode.upsert({
    where: { slug: 'standard' },
    update: {},
    create: {
      name: 'Standard Test',
      slug: 'standard',
      description: '10-12 minutes, 40-50 questions. Best default public test.',
      durationMinutes: 12,
      questionsPerSectionJson: JSON.stringify({
        grammar: 7,
        vocabulary: 7,
        sentence_making: 8,
        listening: 5,
        speaking_readiness: 6,
        real_life_communication: 5,
        learning_behavior: 4,
      }),
      adaptiveEnabled: true,
      leadCaptureRequired: true,
      isActive: true,
    },
  });


  await prisma.testMode.upsert({
    where: { slug: 'quick' },
    update: {},
    create: {
      name: 'Quick Test',
      slug: 'quick',
      description: '5-7 minutes, 25-30 questions. Best for lead generation.',
      durationMinutes: 7,
      questionsPerSectionJson: JSON.stringify({
        grammar: 4, vocabulary: 4, sentence_making: 5,
        listening: 3, speaking_readiness: 4, real_life_communication: 3, learning_behavior: 3,
      }),
      adaptiveEnabled: true,
      leadCaptureRequired: true,
      isActive: true,
    },
  });

  // Delete existing questions to reseed
  await prisma.question.deleteMany({});

  // ============ GRAMMAR QUESTIONS ============
  const grammarQuestions = [
    {
      questionText: 'বাংলা: সে প্রতিদিন ইংরেজি প্র্যাকটিস করে।\nChoose the correct sentence:',
      questionType: 'mcq', category: 'grammar', cefrLevel: 'A1', difficulty: 'easy',
      options: ['He practice English every day.', 'He practices English every day.', 'He is practice English every day.', 'He practiced English every day.'],
      correctAnswer: 'He practices English every day.',
      mistakeTags: ['verb_form_error', 'grammar_foundation_weak'],
      banglaExplanation: 'Third person singular (he/she) এর সাথে present simple-এ verb-এ s/es যোগ হয়।',
    },
    {
      questionText: 'I have lived in Dhaka ____ 2020.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'A2', difficulty: 'easy',
      options: ['for', 'since', 'from', 'by'],
      correctAnswer: 'since',
      mistakeTags: ['preposition_error', 'grammar_foundation_weak'],
      banglaExplanation: 'নির্দিষ্ট সময় (year, month, date) এর আগে since বসে।',
    },

    {
      questionText: 'She ____ to school every day.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'A1', difficulty: 'easy',
      options: ['go', 'goes', 'going', 'gone'],
      correctAnswer: 'goes',
      mistakeTags: ['verb_form_error', 'grammar_foundation_weak'],
      banglaExplanation: 'She/He/It এর সাথে present simple-এ verb-এ s/es যোগ হয়।',
    },
    {
      questionText: 'They ____ playing football when it started raining.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'A2', difficulty: 'medium',
      options: ['was', 'were', 'are', 'is'],
      correctAnswer: 'were',
      mistakeTags: ['tense_error', 'grammar_foundation_weak'],
      banglaExplanation: 'They plural subject, তাই past continuous-এ were ব্যবহৃত হয়।',
    },
    {
      questionText: 'I ____ never been to Cox\'s Bazar.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'A2', difficulty: 'medium',
      options: ['has', 'have', 'had', 'am'],
      correctAnswer: 'have',
      mistakeTags: ['tense_error', 'grammar_foundation_weak'],
      banglaExplanation: 'I/We/They/You এর সাথে present perfect-এ have বসে।',
    },
    {
      questionText: 'Which sentence is grammatically correct?',
      questionType: 'mcq', category: 'grammar', cefrLevel: 'B1', difficulty: 'medium',
      options: ['If I was rich, I will buy a car.', 'If I were rich, I would buy a car.', 'If I am rich, I would buy a car.', 'If I were rich, I will buy a car.'],
      correctAnswer: 'If I were rich, I would buy a car.',
      mistakeTags: ['tense_error', 'grammar_foundation_weak'],
      banglaExplanation: 'Second conditional-এ if clause-এ were এবং main clause-এ would ব্যবহৃত হয়।',
    },

    {
      questionText: 'The meeting ____ already started when I arrived.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'B1', difficulty: 'medium',
      options: ['has', 'had', 'have', 'was'],
      correctAnswer: 'had',
      mistakeTags: ['tense_error', 'grammar_foundation_weak'],
      banglaExplanation: 'Past perfect tense: অতীতের দুটি ঘটনার মধ্যে আগেরটায় had + past participle ব্যবহৃত হয়।',
    },
    {
      questionText: 'Choose the correct passive voice: "Someone stole my phone."',
      questionType: 'mcq', category: 'grammar', cefrLevel: 'B1', difficulty: 'hard',
      options: ['My phone was stolen.', 'My phone is stolen.', 'My phone were stolen.', 'My phone has steal.'],
      correctAnswer: 'My phone was stolen.',
      mistakeTags: ['grammar_foundation_weak'],
      banglaExplanation: 'Past simple passive: was/were + past participle',
    },
    {
      questionText: 'She told me that she ____ come tomorrow.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'B2', difficulty: 'hard',
      options: ['will', 'would', 'can', 'shall'],
      correctAnswer: 'would',
      mistakeTags: ['tense_error', 'grammar_foundation_weak'],
      banglaExplanation: 'Reported speech-এ will পরিবর্তন হয়ে would হয়।',
    },
    {
      questionText: 'Find the error: "He don\'t like coffee."',
      questionType: 'error_spot', category: 'grammar', cefrLevel: 'A1', difficulty: 'easy',
      options: ['He doesn\'t like coffee.', 'He don\'t liked coffee.', 'He not like coffee.', 'He don\'t likes coffee.'],
      correctAnswer: 'He doesn\'t like coffee.',
      mistakeTags: ['verb_form_error', 'grammar_foundation_weak'],
      banglaExplanation: 'He/She/It এর সাথে doesn\'t ব্যবহৃত হয়, don\'t নয়।',
    },
    {
      questionText: 'I am looking forward ____ meeting you.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'B1', difficulty: 'medium',
      options: ['to', 'for', 'at', 'on'],
      correctAnswer: 'to',
      mistakeTags: ['preposition_error', 'grammar_foundation_weak'],
      banglaExplanation: '"Look forward to" একটি fixed phrase—এখানে to এর পর gerund (verb+ing) বসে।',
    },

    {
      questionText: 'Neither the teacher nor the students ____ present.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'B2', difficulty: 'hard',
      options: ['was', 'were', 'is', 'are'],
      correctAnswer: 'were',
      mistakeTags: ['grammar_foundation_weak'],
      banglaExplanation: 'Neither...nor-এ verb টি nearest subject অনুযায়ী হয়। students plural তাই were।',
    },
    {
      questionText: 'I ____ English for 3 years now.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'A2', difficulty: 'medium',
      options: ['learn', 'am learning', 'have been learning', 'learned'],
      correctAnswer: 'have been learning',
      mistakeTags: ['tense_error', 'grammar_foundation_weak'],
      banglaExplanation: 'অতীত থেকে শুরু হয়ে এখনো চলছে—present perfect continuous: have been + verb-ing',
    },
    {
      questionText: 'She asked me where I ____.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'B2', difficulty: 'hard',
      options: ['live', 'lived', 'am living', 'do live'],
      correctAnswer: 'lived',
      mistakeTags: ['tense_error', 'grammar_foundation_weak'],
      banglaExplanation: 'Reported speech-এ present simple পরিবর্তন হয়ে past simple হয়।',
    },
    {
      questionText: 'Which sentence uses "used to" correctly?',
      questionType: 'mcq', category: 'grammar', cefrLevel: 'A2', difficulty: 'medium',
      options: ['I used to go school.', 'I used to go to school every day.', 'I use to go to school.', 'I used going to school.'],
      correctAnswer: 'I used to go to school every day.',
      mistakeTags: ['grammar_foundation_weak'],
      banglaExplanation: '"Used to + base verb" অতীতের habit বোঝাতে ব্যবহৃত হয়।',
    },
    {
      questionText: 'The book ____ is on the table is mine.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'B1', difficulty: 'medium',
      options: ['who', 'which', 'whom', 'where'],
      correctAnswer: 'which',
      mistakeTags: ['grammar_foundation_weak'],
      banglaExplanation: 'Non-person/thing এর জন্য relative clause-এ which ব্যবহৃত হয়।',
    },
    {
      questionText: 'By next year, I ____ graduated from university.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'B2', difficulty: 'hard',
      options: ['will', 'will have', 'would', 'have'],
      correctAnswer: 'will have',
      mistakeTags: ['tense_error', 'grammar_foundation_weak'],
      banglaExplanation: 'Future perfect: ভবিষ্যতে কোনো সময়ের আগে শেষ হবে—will have + past participle',
    },
    {
      questionText: 'I wish I ____ taller.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'B1', difficulty: 'medium',
      options: ['am', 'was', 'were', 'be'],
      correctAnswer: 'were',
      mistakeTags: ['grammar_foundation_weak'],
      banglaExplanation: 'Wish + past subjunctive-এ সবার সাথে were ব্যবহৃত হয়।',
    },
    {
      questionText: 'He runs ____ than his brother.',
      questionType: 'fill_blank', category: 'grammar', cefrLevel: 'A1', difficulty: 'easy',
      options: ['fast', 'faster', 'fastest', 'more fast'],
      correctAnswer: 'faster',
      mistakeTags: ['grammar_foundation_weak'],
      banglaExplanation: 'Comparative form: short adjective/adverb + er (faster, taller, etc.)',
    },
  ];


  // ============ VOCABULARY QUESTIONS ============
  const vocabularyQuestions = [
    {
      questionText: '"I\'m running late" means:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'A2', difficulty: 'easy',
      options: ['আমি দৌড়াচ্ছি', 'আমার দেরি হচ্ছে', 'আমি অসুস্থ', 'আমি বাসায় আছি'],
      correctAnswer: 'আমার দেরি হচ্ছে',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: '"Running late" একটি common phrase যার অর্থ দেরি হচ্ছে।',
    },
    {
      questionText: 'I want to ____ my speaking skill.',
      questionType: 'fill_blank', category: 'vocabulary', cefrLevel: 'A1', difficulty: 'easy',
      options: ['improve', 'borrow', 'break', 'carry'],
      correctAnswer: 'improve',
      mistakeTags: ['active_vocabulary_weak'],
      banglaExplanation: 'Improve = উন্নতি করা। Skill improve করা common collocation।',
    },
    {
      questionText: 'Choose the most natural phrase:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'A2', difficulty: 'medium',
      options: ['do a decision', 'make a decision', 'give a decision', 'create a decision'],
      correctAnswer: 'make a decision',
      mistakeTags: ['collocation_weak', 'active_vocabulary_weak'],
      banglaExplanation: '"Make a decision" সঠিক collocation। Decision-এর সাথে make বসে।',
    },
    {
      questionText: '"Break the ice" means:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'B1', difficulty: 'medium',
      options: ['বরফ ভাঙা', 'কথোপকথন শুরু করা', 'ঝগড়া করা', 'চুপ থাকা'],
      correctAnswer: 'কথোপকথন শুরু করা',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: '"Break the ice" = awkward silence ভাঙা, কথোপকথন শুরু করা।',
    },
    {
      questionText: 'The deadline is tomorrow. "Deadline" means:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'A2', difficulty: 'easy',
      options: ['মৃত্যু', 'শেষ সময়সীমা', 'ছুটি', 'সকাল'],
      correctAnswer: 'শেষ সময়সীমা',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: 'Deadline = কাজ জমা দেওয়ার শেষ সময়।',
    },

    {
      questionText: 'He is very ____ about his new job. (excited/exciting)',
      questionType: 'fill_blank', category: 'vocabulary', cefrLevel: 'A2', difficulty: 'medium',
      options: ['excited', 'exciting', 'excite', 'excitedly'],
      correctAnswer: 'excited',
      mistakeTags: ['active_vocabulary_weak'],
      banglaExplanation: '-ed form ব্যক্তির feeling বোঝায়, -ing form জিনিসের quality বোঝায়।',
    },
    {
      questionText: 'Select the word that means "to suggest or offer":',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'A1', difficulty: 'easy',
      options: ['propose', 'oppose', 'dispose', 'impose'],
      correctAnswer: 'propose',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: 'Propose = প্রস্তাব করা, suggest করা।',
    },
    {
      questionText: '"Can you give me a hand?" means:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'A2', difficulty: 'easy',
      options: ['আমাকে তোমার হাত দাও', 'আমাকে সাহায্য কর', 'হ্যান্ডশেক কর', 'আমার হাত ধর'],
      correctAnswer: 'আমাকে সাহায্য কর',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: '"Give a hand" = সাহায্য করা, help করা।',
    },
    {
      questionText: 'I need to ____ an appointment with the doctor.',
      questionType: 'fill_blank', category: 'vocabulary', cefrLevel: 'B1', difficulty: 'medium',
      options: ['make', 'do', 'have', 'take'],
      correctAnswer: 'make',
      mistakeTags: ['collocation_weak', 'active_vocabulary_weak'],
      banglaExplanation: '"Make an appointment" সঠিক collocation।',
    },
    {
      questionText: '"Fluent" means:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'A1', difficulty: 'easy',
      options: ['ধীরে কথা বলা', 'সাবলীলভাবে কথা বলা', 'চুপ থাকা', 'জোরে কথা বলা'],
      correctAnswer: 'সাবলীলভাবে কথা বলা',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: 'Fluent = সাবলীল, smoothly কথা বলতে পারা।',
    },
    {
      questionText: 'She has a good ____ of English vocabulary. (knowledge/information)',
      questionType: 'fill_blank', category: 'vocabulary', cefrLevel: 'B1', difficulty: 'medium',
      options: ['knowledge', 'information', 'news', 'data'],
      correctAnswer: 'knowledge',
      mistakeTags: ['collocation_weak', 'active_vocabulary_weak'],
      banglaExplanation: '"Knowledge of" correct collocation। Information countable না, এবং বিষয় সম্পর্কে "knowledge" ব্যবহৃত হয়।',
    },

    {
      questionText: '"Nevertheless" is similar to:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'B2', difficulty: 'hard',
      options: ['because', 'however', 'therefore', 'unless'],
      correctAnswer: 'however',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: 'Nevertheless = তা সত্ত্বেও, however-এর মতো contrast বোঝায়।',
    },
    {
      questionText: 'The project was ____. We finished it in time.',
      questionType: 'fill_blank', category: 'vocabulary', cefrLevel: 'B1', difficulty: 'medium',
      options: ['successful', 'succeed', 'success', 'successfully'],
      correctAnswer: 'successful',
      mistakeTags: ['active_vocabulary_weak'],
      banglaExplanation: 'Adjective হিসেবে successful ব্যবহৃত হয়। Was-এর পর adjective বসে।',
    },
    {
      questionText: '"Take it for granted" means:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'B2', difficulty: 'hard',
      options: ['কৃতজ্ঞ হওয়া', 'মূল্য না দেওয়া / স্বাভাবিক ভাবা', 'ধার নেওয়া', 'ফেরত দেওয়া'],
      correctAnswer: 'মূল্য না দেওয়া / স্বাভাবিক ভাবা',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: '"Take for granted" = কোনো কিছুর মূল্য না দেওয়া, সবসময় থাকবে ভেবে নেওয়া।',
    },
    {
      questionText: 'I will ____ you back later. (call)',
      questionType: 'fill_blank', category: 'vocabulary', cefrLevel: 'A1', difficulty: 'easy',
      options: ['call', 'tell', 'say', 'speak'],
      correctAnswer: 'call',
      mistakeTags: ['active_vocabulary_weak'],
      banglaExplanation: '"Call back" = পরে ফোন করা।',
    },
    {
      questionText: '"I\'m on my way" means:',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'A2', difficulty: 'easy',
      options: ['আমি পথে আছি', 'আমি হারিয়ে গেছি', 'আমি বাসায় আছি', 'আমি দেরি করব'],
      correctAnswer: 'আমি পথে আছি',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: '"On my way" = আসছি, পথে আছি।',
    },
    {
      questionText: 'Choose the opposite of "generous":',
      questionType: 'mcq', category: 'vocabulary', cefrLevel: 'B1', difficulty: 'medium',
      options: ['kind', 'selfish', 'brave', 'calm'],
      correctAnswer: 'selfish',
      mistakeTags: ['vocabulary_weak'],
      banglaExplanation: 'Generous = উদার, বিপরীত selfish = স্বার্থপর।',
    },
    {
      questionText: 'He gave a very ____ presentation. Everyone understood it.',
      questionType: 'fill_blank', category: 'vocabulary', cefrLevel: 'B1', difficulty: 'medium',
      options: ['clear', 'hardly', 'fast', 'loud'],
      correctAnswer: 'clear',
      mistakeTags: ['active_vocabulary_weak'],
      banglaExplanation: 'Clear presentation = স্পষ্ট presentation যা সবাই বুঝতে পেরেছে।',
    },
  ];


  // ============ SENTENCE MAKING QUESTIONS ============
  const sentenceMakingQuestions = [
    {
      questionText: 'বাংলা: আমি কাল আপনার সাথে কথা বলবো।\nবাস্তবে আপনি কোন sentence বলতেন?',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'A2', difficulty: 'easy',
      options: ['I will talk to you tomorrow.', 'I talk with you yesterday.', 'I am talked to you tomorrow.', 'I will speaking you tomorrow.'],
      correctAnswer: 'I will talk to you tomorrow.',
      mistakeTags: ['sentence_making_weak', 'tense_error'],
      banglaExplanation: 'Future simple: will + base verb. "I will talk to you tomorrow."',
    },
    {
      questionText: 'Arrange: want / improve / I / to / English / my',
      questionType: 'word_order', category: 'sentence_making', cefrLevel: 'A1', difficulty: 'easy',
      options: ['I want to improve my English.', 'I improve want to my English.', 'Want I to improve my English.', 'My English I want to improve.'],
      correctAnswer: 'I want to improve my English.',
      mistakeTags: ['word_order_error', 'sentence_making_weak'],
      banglaExplanation: 'Subject + verb + to + verb + object: I want to improve my English.',
    },
    {
      questionText: 'Client-কে বলতে চান: "আমি কাজটা কাল পাঠিয়ে দিব।"\nবাস্তবে আপনি কী বলতেন?',
      questionType: 'scenario_mcq', category: 'sentence_making', cefrLevel: 'A2', difficulty: 'medium',
      options: ['I will send the work tomorrow.', 'I send work yesterday.', 'I am send tomorrow.', 'I will sent the work tomorrow.'],
      correctAnswer: 'I will send the work tomorrow.',
      mistakeTags: ['client_response_weak', 'sentence_making_weak'],
      banglaExplanation: 'will + base verb (send, NOT sent).',
    },
    {
      questionText: 'বাংলা: আমার ইংরেজিতে কথা বলতে ভয় লাগে।\nTranslate:',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'A2', difficulty: 'medium',
      options: ['I am afraid of speaking in English.', 'I afraid speaking English.', 'I am fear to speak English.', 'English speaking I afraid.'],
      correctAnswer: 'I am afraid of speaking in English.',
      mistakeTags: ['sentence_making_weak', 'bangla_to_english_conversion_weak'],
      banglaExplanation: '"Afraid of + gerund" structure ব্যবহৃত হয়।',
    },

    {
      questionText: 'Arrange: is / name / my / Rahim',
      questionType: 'word_order', category: 'sentence_making', cefrLevel: 'A1', difficulty: 'easy',
      options: ['My name is Rahim.', 'Is my name Rahim.', 'Rahim is my name.', 'Name my is Rahim.'],
      correctAnswer: 'My name is Rahim.',
      mistakeTags: ['word_order_error', 'sentence_making_weak'],
      banglaExplanation: 'Basic self-introduction: My name is + name.',
    },
    {
      questionText: 'বাংলা: সে ঢাকায় থাকে।\nChoose the correct sentence:',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'A1', difficulty: 'easy',
      options: ['He lives in Dhaka.', 'He live in Dhaka.', 'He is live in Dhaka.', 'He living Dhaka.'],
      correctAnswer: 'He lives in Dhaka.',
      mistakeTags: ['sentence_making_weak', 'verb_form_error'],
      banglaExplanation: 'Present simple + third person: He lives (not live).',
    },
    {
      questionText: 'বাংলা: আমি গতকাল বাজারে গিয়েছিলাম।\nChoose:',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'A2', difficulty: 'medium',
      options: ['I went to the market yesterday.', 'I go market yesterday.', 'I was go to market.', 'Yesterday market I went.'],
      correctAnswer: 'I went to the market yesterday.',
      mistakeTags: ['sentence_making_weak', 'tense_error'],
      banglaExplanation: 'Past simple: Subject + past verb. "I went to the market yesterday."',
    },
    {
      questionText: 'Complete: "Could you please ____ me the document?"',
      questionType: 'fill_blank', category: 'sentence_making', cefrLevel: 'A2', difficulty: 'medium',
      options: ['send', 'sending', 'sent', 'sends'],
      correctAnswer: 'send',
      mistakeTags: ['sentence_making_weak'],
      banglaExplanation: 'Could you please + base verb (send).',
    },
    {
      questionText: 'বাংলা: আমি ৫ বছর ধরে ইংরেজি শিখছি।\nChoose the best translation:',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'B1', difficulty: 'hard',
      options: ['I have been learning English for 5 years.', 'I learn English 5 years.', 'I am learn English since 5 years.', 'English I learning 5 years.'],
      correctAnswer: 'I have been learning English for 5 years.',
      mistakeTags: ['sentence_making_weak', 'tense_error', 'bangla_to_english_conversion_weak'],
      banglaExplanation: 'Present perfect continuous: have been + verb-ing + for + duration.',
    },
    {
      questionText: 'Arrange: should / what / do / I / ?',
      questionType: 'word_order', category: 'sentence_making', cefrLevel: 'A1', difficulty: 'easy',
      options: ['What should I do?', 'I should what do?', 'Should I what do?', 'Do I should what?'],
      correctAnswer: 'What should I do?',
      mistakeTags: ['word_order_error', 'sentence_making_weak'],
      banglaExplanation: 'WH-question + modal + subject + verb: What should I do?',
    },

    {
      questionText: 'বাংলা: তার সাথে আমার দেখা হয়নি।\nBest translation:',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'B1', difficulty: 'medium',
      options: ['I haven\'t met him.', 'I not met him.', 'I didn\'t met him.', 'Him I not meeting.'],
      correctAnswer: 'I haven\'t met him.',
      mistakeTags: ['sentence_making_weak', 'tense_error'],
      banglaExplanation: 'Present perfect negative: haven\'t + past participle.',
    },
    {
      questionText: 'বাংলা: যদি আমি জানতাম, তাহলে বলতাম।\nChoose:',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'B2', difficulty: 'hard',
      options: ['If I had known, I would have told you.', 'If I know, I tell you.', 'If I knew, I tell.', 'I know if, I told you.'],
      correctAnswer: 'If I had known, I would have told you.',
      mistakeTags: ['sentence_making_weak', 'tense_error'],
      banglaExplanation: 'Third conditional: If + past perfect, would have + past participle.',
    },
    {
      questionText: 'Complete the professional email: "I am writing to ____ about the project update."',
      questionType: 'fill_blank', category: 'sentence_making', cefrLevel: 'B1', difficulty: 'medium',
      options: ['inquire', 'asking', 'tell', 'say'],
      correctAnswer: 'inquire',
      mistakeTags: ['sentence_making_weak', 'client_response_weak'],
      banglaExplanation: '"I am writing to inquire" formal email-এর common opening.',
    },
    {
      questionText: 'বাংলা: আমি তোমাকে help করতে পারি।\nChoose:',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'A1', difficulty: 'easy',
      options: ['I can help you.', 'I help can you.', 'Can I you help.', 'I am can help.'],
      correctAnswer: 'I can help you.',
      mistakeTags: ['sentence_making_weak', 'word_order_error'],
      banglaExplanation: 'Modal verb: Subject + can + base verb + object.',
    },
    {
      questionText: 'Arrange: have / do / how / brothers / you / many / ?',
      questionType: 'word_order', category: 'sentence_making', cefrLevel: 'A1', difficulty: 'easy',
      options: ['How many brothers do you have?', 'Do you have how many brothers?', 'You have how many brothers?', 'Brothers how many you have?'],
      correctAnswer: 'How many brothers do you have?',
      mistakeTags: ['word_order_error', 'sentence_making_weak'],
      banglaExplanation: 'How many + noun + do/does + subject + verb: How many brothers do you have?',
    },
    {
      questionText: 'বাংলা: আমি English fluently বলতে চাই।\nBest sentence:',
      questionType: 'mcq', category: 'sentence_making', cefrLevel: 'A2', difficulty: 'easy',
      options: ['I want to speak English fluently.', 'I want speak English fluent.', 'I speaking English want fluent.', 'English fluently I want speak.'],
      correctAnswer: 'I want to speak English fluently.',
      mistakeTags: ['sentence_making_weak'],
      banglaExplanation: 'want + to + base verb + object + adverb.',
    },
    {
      questionText: 'বাংলা: আপনি কি আমাকে ১ দিন extra সময় দিতে পারবেন?\nProfessional version:',
      questionType: 'scenario_mcq', category: 'sentence_making', cefrLevel: 'B1', difficulty: 'medium',
      options: ['Could you please give me one extra day?', 'Give me 1 day more.', 'I need day extra please.', 'You give me extra day can?'],
      correctAnswer: 'Could you please give me one extra day?',
      mistakeTags: ['sentence_making_weak', 'client_response_weak'],
      banglaExplanation: 'Polite request: Could you please + base verb.',
    },
  ];


  // ============ LISTENING QUESTIONS ============
  const listeningQuestions = [
    {
      questionText: 'Audio: "I usually wake up at six, but today I woke up at eight."\nWhen did he wake up today?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'A1', difficulty: 'easy',
      options: ['6', '7', '8', '9'],
      correctAnswer: '8',
      mistakeTags: ['listening_weak'],
      audioUrl: 'tts:I usually wake up at six, but today I woke up at eight.',
      banglaExplanation: 'Audio transcript: "I usually wake up at six, but today I woke up at eight."\n\n"Today I woke up at eight" — আজ ৮টায় উঠেছে।',
    },
    {
      questionText: 'Audio: "Can you send me the updated design by tomorrow morning?"\nWhat does the client want?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'A2', difficulty: 'medium',
      options: ['Old design', 'Updated design', 'Invoice', 'Meeting link'],
      correctAnswer: 'Updated design',
      mistakeTags: ['client_listening_weak', 'listening_weak'],
      audioUrl: 'tts:Can you send me the updated design by tomorrow morning?',
      banglaExplanation: 'Audio transcript: "Can you send me the updated design by tomorrow morning?"\n\n"Updated design by tomorrow morning" — আপডেটেড ডিজাইন চাচ্ছে।',
    },
    {
      questionText: 'Audio: "The meeting has been rescheduled to 3 PM."\nWhat happened to the meeting?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'A2', difficulty: 'easy',
      options: ['Cancelled', 'Time changed to 3 PM', 'Moved to tomorrow', 'Started early'],
      correctAnswer: 'Time changed to 3 PM',
      mistakeTags: ['listening_weak'],
      audioUrl: 'tts:The meeting has been rescheduled to 3 PM.',
      banglaExplanation: 'Audio transcript: "The meeting has been rescheduled to 3 PM."\n\nRescheduled = সময় পরিবর্তন হয়েছে, ৩ PM এ।',
    },
    {
      questionText: 'Audio: "I\'ve been working here for about three years now."\nHow long has the person worked here?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'A2', difficulty: 'easy',
      options: ['1 year', '2 years', '3 years', '4 years'],
      correctAnswer: '3 years',
      mistakeTags: ['listening_weak'],
      audioUrl: 'tts:I\'ve been working here for about three years now.',
      banglaExplanation: 'Audio transcript: "I\'ve been working here for about three years now."\n\n"About three years" — প্রায় ৩ বছর।',
    },
    {
      questionText: 'Audio: "Could you send me the invoice by Friday at the latest?"\nWhat is the deadline?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'B1', difficulty: 'medium',
      options: ['Monday', 'Wednesday', 'Friday', 'Sunday'],
      correctAnswer: 'Friday',
      mistakeTags: ['listening_weak', 'client_listening_weak'],
      audioUrl: 'tts:Could you send me the invoice by Friday at the latest?',
      banglaExplanation: 'Audio transcript: "Could you send me the invoice by Friday at the latest?"\n\n"By Friday at the latest" — শুক্রবারের মধ্যে।',
    },

    {
      questionText: 'Audio: "I\'m sorry, but I won\'t be able to attend the meeting tomorrow."\nWhat is the speaker saying?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'B1', difficulty: 'medium',
      options: ['They will attend', 'They cannot attend tomorrow', 'They want to reschedule', 'They are late'],
      correctAnswer: 'They cannot attend tomorrow',
      mistakeTags: ['listening_weak'],
      audioUrl: 'tts:I\'m sorry, but I won\'t be able to attend the meeting tomorrow.',
      banglaExplanation: 'Audio transcript: "I\'m sorry, but I won\'t be able to attend the meeting tomorrow."\n\n"Won\'t be able to attend" — আসতে পারবে না।',
    },
    {
      questionText: 'Audio: "The restaurant is on the left side, just past the bank."\nWhere is the restaurant?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'A1', difficulty: 'easy',
      options: ['Right side before bank', 'Left side past the bank', 'Behind the bank', 'Next to the school'],
      correctAnswer: 'Left side past the bank',
      mistakeTags: ['listening_weak'],
      audioUrl: 'tts:The restaurant is on the left side, just past the bank.',
      banglaExplanation: 'Audio transcript: "The restaurant is on the left side, just past the bank."\n\n"On the left side, just past the bank" — bank পার হলে বাম পাশে।',
    },
    {
      questionText: 'Audio: "Please let me know if you need any changes to the proposal."\nWhat is the speaker asking?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'B1', difficulty: 'medium',
      options: ['Send the proposal', 'Tell if changes needed', 'Delete the proposal', 'Accept the proposal'],
      correctAnswer: 'Tell if changes needed',
      mistakeTags: ['listening_weak', 'client_listening_weak'],
      audioUrl: 'tts:Please let me know if you need any changes to the proposal.',
      banglaExplanation: 'Audio transcript: "Please let me know if you need any changes to the proposal."\n\n"Let me know if you need changes" — পরিবর্তন লাগলে জানান।',
    },
    {
      questionText: 'Audio: "I think we should postpone the launch until next month."\nWhat does postpone mean here?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'B2', difficulty: 'hard',
      options: ['Start now', 'Cancel completely', 'Delay to next month', 'Speed up'],
      correctAnswer: 'Delay to next month',
      mistakeTags: ['listening_weak', 'vocabulary_weak'],
      audioUrl: 'tts:I think we should postpone the launch until next month.',
      banglaExplanation: 'Audio transcript: "I think we should postpone the launch until next month."\n\nPostpone = পিছিয়ে দেওয়া, delay করা।',
    },
    {
      questionText: 'Audio: "First, turn right, then go straight. It\'s the third building on your left."\nWhich building?',
      questionType: 'audio_mcq', category: 'listening', cefrLevel: 'A2', difficulty: 'medium',
      options: ['First on right', 'Second on left', 'Third on left', 'Fourth on right'],
      correctAnswer: 'Third on left',
      mistakeTags: ['listening_weak', 'connected_speech_weak'],
      audioUrl: 'tts:First, turn right, then go straight. It\'s the third building on your left.',
      banglaExplanation: 'Audio transcript: "First, turn right, then go straight. It\'s the third building on your left."\n\n"Third building on your left" — বাম পাশে তৃতীয় building।',
    },
  ];


  // ============ SPEAKING READINESS QUESTIONS ============
  const speakingQuestions = [
    {
      questionText: 'আপনি ইংরেজিতে কথা বলতে গেলে কেমন feel করেন?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'A1', difficulty: 'easy',
      options: ['ভয় লাগে, চুপ হয়ে যাই', 'বলতে চাই কিন্তু sentence আসে না', 'ধীরে ধীরে বলতে পারি', 'Confidently বলতে পারি'],
      correctAnswer: 'Confidently বলতে পারি',
      mistakeTags: ['confidence_low', 'fear_of_mistake'],
      banglaExplanation: 'এটি আপনার speaking confidence level বোঝার জন্য।',
    },
    {
      questionText: 'গত ৭ দিনে আপনি কয়দিন English speaking practice করেছেন?',
      questionType: 'habit', category: 'speaking_readiness', cefrLevel: 'A1', difficulty: 'easy',
      options: ['0 দিন', '1–2 দিন', '3–4 দিন', '5–7 দিন'],
      correctAnswer: '5–7 দিন',
      mistakeTags: ['practice_habit_weak', 'consistency_weak'],
      banglaExplanation: 'Regular speaking practice fluency-র জন্য অত্যন্ত গুরুত্বপূর্ণ।',
    },
    {
      questionText: 'কেউ English-এ কিছু জিজ্ঞেস করলে আপনি কী করেন?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'A2', difficulty: 'easy',
      options: ['চুপ থাকি / এড়িয়ে যাই', 'বাংলায় উত্তর দিই', 'ভাঙা ভাঙা English-এ বলার চেষ্টা করি', 'Confidently English-এ উত্তর দিই'],
      correctAnswer: 'Confidently English-এ উত্তর দিই',
      mistakeTags: ['confidence_low', 'fear_of_mistake'],
      banglaExplanation: 'Real-life response আপনার actual speaking readiness বোঝায়।',
    },
    {
      questionText: 'আপনার English speaking-এর সবচেয়ে বড় সমস্যা কী?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'A1', difficulty: 'easy',
      options: ['Sentence বানাতে পারি না', 'Word মনে আসে না', 'ভুল হওয়ার ভয়', 'কোনো সমস্যা নেই'],
      correctAnswer: 'কোনো সমস্যা নেই',
      mistakeTags: ['sentence_making_weak', 'confidence_low', 'fear_of_mistake'],
      banglaExplanation: 'আপনার main barrier চিহ্নিত করা গুরুত্বপূর্ণ।',
    },
    {
      questionText: 'Phone-এ English-এ কথা বলতে হলে আপনার কেমন লাগে?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'A2', difficulty: 'medium',
      options: ['অনেক nervous হই', 'Prepare করে বলি', 'মোটামুটি পারি', 'Comfortably পারি'],
      correctAnswer: 'Comfortably পারি',
      mistakeTags: ['confidence_low'],
      banglaExplanation: 'Phone conversation real speaking confidence-এর good indicator.',
    },

    {
      questionText: 'আপনি কি mirror-এর সামনে বা alone English practice করেন?',
      questionType: 'habit', category: 'speaking_readiness', cefrLevel: 'A1', difficulty: 'easy',
      options: ['কখনো করিনি', 'মাঝে মাঝে', 'প্রায় প্রতিদিন', 'প্রতিদিন নিয়মিত'],
      correctAnswer: 'প্রতিদিন নিয়মিত',
      mistakeTags: ['practice_habit_weak'],
      banglaExplanation: 'Solo practice habit fluency build করতে সাহায্য করে।',
    },
    {
      questionText: '৩০ সেকেন্ডে নিজের পরিচয় English-এ দিতে পারবেন?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'A2', difficulty: 'medium',
      options: ['পারি না', 'অনেক struggle করে একটু পারি', 'ধীরে ধীরে পারি', 'সহজেই পারি'],
      correctAnswer: 'সহজেই পারি',
      mistakeTags: ['sentence_making_weak', 'confidence_low'],
      banglaExplanation: 'Self-introduction ability basic speaking readiness-এর indicator.',
    },
    {
      questionText: 'আপনি কি English movies/videos subtitles ছাড়া বুঝতে পারেন?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'B1', difficulty: 'medium',
      options: ['একদম পারি না', 'কিছু কিছু words বুঝি', 'মোটামুটি main idea বুঝি', 'বেশিরভাগ বুঝি'],
      correctAnswer: 'বেশিরভাগ বুঝি',
      mistakeTags: ['listening_weak', 'connected_speech_weak'],
      banglaExplanation: 'Subtitle-free comprehension listening + vocabulary strength বোঝায়।',
    },
    {
      questionText: 'আপনি যখন English বলেন, তখন কি বাংলায় আগে ভাবেন?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'A2', difficulty: 'easy',
      options: ['সবসময় বাংলায় ভাবি তারপর translate করি', 'বেশিরভাগ সময়', 'মাঝে মাঝে', 'সরাসরি English-এ ভাবি'],
      correctAnswer: 'সরাসরি English-এ ভাবি',
      mistakeTags: ['bangla_to_english_conversion_weak'],
      banglaExplanation: 'Thinking in English fluency-র important sign.',
    },
    {
      questionText: 'নতুন কারো সাথে English-এ পরিচিত হতে হলে আপনি:',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'A2', difficulty: 'easy',
      options: ['এড়িয়ে যাই', 'অনেক nervous feel করি', 'একটু চেষ্টা করি', 'স্বাভাবিকভাবে পারি'],
      correctAnswer: 'স্বাভাবিকভাবে পারি',
      mistakeTags: ['confidence_low', 'fear_of_mistake'],
      banglaExplanation: 'Social speaking confidence real-world readiness indicator.',
    },
    {
      questionText: 'IELTS বা formal speaking test দিতে হলে আপনার preparation কেমন মনে হয়?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'B1', difficulty: 'medium',
      options: ['একদমই ready না', 'অনেক preparation দরকার', 'কিছুটা ready', 'Mostly ready'],
      correctAnswer: 'Mostly ready',
      mistakeTags: ['confidence_low', 'ielts_response_weak'],
      banglaExplanation: 'Test readiness perception overall speaking confidence level indicate করে।',
    },
    {
      questionText: 'English-এ কথা বলতে গিয়ে ভুল হলে আপনি কী করেন?',
      questionType: 'self_assessment', category: 'speaking_readiness', cefrLevel: 'A2', difficulty: 'easy',
      options: ['লজ্জায় চুপ হয়ে যাই', 'অনেক nervous হই কিন্তু চালিয়ে যাই', 'Self-correct করে আবার বলি', 'Normal মনে করি, চালিয়ে যাই'],
      correctAnswer: 'Normal মনে করি, চালিয়ে যাই',
      mistakeTags: ['fear_of_mistake', 'confidence_low'],
      banglaExplanation: 'Error recovery attitude speaking growth-এর জন্য crucial.',
    },
    {
      questionText: 'আপনি কি Shadowing practice (কারো কথা repeat করা) করেন?',
      questionType: 'habit', category: 'speaking_readiness', cefrLevel: 'A2', difficulty: 'easy',
      options: ['জানি না এটা কী', 'জানি কিন্তু করি না', 'মাঝে মাঝে করি', 'নিয়মিত করি'],
      correctAnswer: 'নিয়মিত করি',
      mistakeTags: ['practice_habit_weak'],
      banglaExplanation: 'Shadowing pronunciation ও fluency-র best practice method.',
    },
  ];


  // ============ REAL-LIFE COMMUNICATION QUESTIONS ============
  const realLifeQuestions = [
    {
      questionText: 'Client বলল: "Can you revise this design?"\nআপনি বাস্তবে কী বলতেন?',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'A2', difficulty: 'medium',
      options: ['Yes, I can revise it and send the updated version soon.', 'Yes, I revision this.', 'I am revised now.', 'You send me revise.'],
      correctAnswer: 'Yes, I can revise it and send the updated version soon.',
      mistakeTags: ['client_response_weak'],
      banglaExplanation: 'Professional response: Acknowledge + confirm action + timeline.',
    },
    {
      questionText: '"Tell me about yourself" — Job interview-এ best answer শুরু কোনটা?',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'B1', difficulty: 'medium',
      options: ['Myself Rahim.', 'I am Rahim and I have 3 years of experience in sales.', 'My name is coming Rahim.', 'I born in Bangladesh 1995.'],
      correctAnswer: 'I am Rahim and I have 3 years of experience in sales.',
      mistakeTags: ['interview_response_weak'],
      banglaExplanation: 'Professional self-intro: Name + experience/skills.',
    },
    {
      questionText: 'Boss-কে বলতে চান: "আমি report টা আজকের মধ্যে পাঠিয়ে দিব।"',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'A2', difficulty: 'easy',
      options: ['I will send the report by today.', 'I send report yesterday.', 'I am send the report.', 'I will sent today report.'],
      correctAnswer: 'I will send the report by today.',
      mistakeTags: ['professional_communication_weak'],
      banglaExplanation: '"will send by today" — professional future commitment.',
    },
    {
      questionText: 'Client জিজ্ঞেস করল: "What is your rate for this project?"\nBest professional response:',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'B1', difficulty: 'medium',
      options: ['My rate for this project would be $X, and it includes Y and Z.', 'Money give me $100.', 'Rate is many. How much you pay?', 'I am charge project.'],
      correctAnswer: 'My rate for this project would be $X, and it includes Y and Z.',
      mistakeTags: ['client_response_weak'],
      banglaExplanation: 'Rate discussion: State rate + explain what\'s included.',
    },
    {
      questionText: 'IELTS Speaking Part 2 answer long করতে কী দরকার?',
      questionType: 'mcq', category: 'real_life_communication', cefrLevel: 'B1', difficulty: 'medium',
      options: ['শুধু one-word answer', 'Reason, example, details', 'শুধু grammar rule', 'দ্রুত শেষ করা'],
      correctAnswer: 'Reason, example, details',
      mistakeTags: ['ielts_response_weak'],
      banglaExplanation: 'Extended response = reason + example + details/feeling.',
    },

    {
      questionText: 'Client বলল: "I need this done urgently."\nBest response:',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'B1', difficulty: 'medium',
      options: ['I understand the urgency. Let me prioritize this and get back to you with a timeline.', 'OK done.', 'Urgent why? I busy.', 'I am do urgent.'],
      correctAnswer: 'I understand the urgency. Let me prioritize this and get back to you with a timeline.',
      mistakeTags: ['client_response_weak'],
      banglaExplanation: 'Acknowledge urgency + promise action + timeline — professional.',
    },
    {
      questionText: 'Office meeting-এ আপনার opinion দিতে হলে কোনটা best?',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'B1', difficulty: 'medium',
      options: ['In my opinion, I think we should...', 'I say no.', 'Opinion mine is different.', 'No good this idea.'],
      correctAnswer: 'In my opinion, I think we should...',
      mistakeTags: ['professional_communication_weak'],
      banglaExplanation: '"In my opinion" / "I think we should" — polite opinion expression.',
    },
    {
      questionText: 'কেউ বলল: "Nice to meet you." আপনি কী বলবেন?',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'A1', difficulty: 'easy',
      options: ['Nice to meet you too.', 'I am meet you.', 'Thank you meeting.', 'Yes.'],
      correctAnswer: 'Nice to meet you too.',
      mistakeTags: ['real_life_communication_weak'],
      banglaExplanation: 'Standard greeting response: "Nice to meet you too."',
    },
    {
      questionText: 'Deadline miss হবে বুঝতে পেরে client-কে কীভাবে জানাবেন?',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'B2', difficulty: 'hard',
      options: ['I wanted to let you know that I might need an extra day. I\'ll keep you updated.', 'Late. Sorry.', 'I am late give day.', 'Deadline I cannot.'],
      correctAnswer: 'I wanted to let you know that I might need an extra day. I\'ll keep you updated.',
      mistakeTags: ['client_response_weak'],
      banglaExplanation: 'Proactive communication: Inform early + apologize + update promise.',
    },
    {
      questionText: 'Job interview শেষে interviewer জিজ্ঞেস করল: "Do you have any questions?"\nBest response:',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'B1', difficulty: 'medium',
      options: ['Yes, could you tell me more about the team culture and growth opportunities?', 'No.', 'Question I have not.', 'When salary?'],
      correctAnswer: 'Yes, could you tell me more about the team culture and growth opportunities?',
      mistakeTags: ['interview_response_weak'],
      banglaExplanation: 'Asking thoughtful questions shows interest and professionalism.',
    },
    {
      questionText: 'বিদেশে shop-এ কিছু কিনতে গিয়ে: "How much is this?"',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'A1', difficulty: 'easy',
      options: ['How much is this?', 'This money how?', 'Price tell.', 'What cost this thing?'],
      correctAnswer: 'How much is this?',
      mistakeTags: ['real_life_communication_weak'],
      banglaExplanation: '"How much is this?" — standard shopping question.',
    },
    {
      questionText: 'Colleague-কে help চাইতে চান: "একটু help করবেন?"',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'A2', difficulty: 'easy',
      options: ['Could you help me with this, please?', 'Help me.', 'You help.', 'Give help please.'],
      correctAnswer: 'Could you help me with this, please?',
      mistakeTags: ['professional_communication_weak'],
      banglaExplanation: 'Polite request: Could you + verb + please?',
    },
    {
      questionText: 'Client feedback দিল: "This is not what I expected."\nBest professional response:',
      questionType: 'scenario_mcq', category: 'real_life_communication', cefrLevel: 'B2', difficulty: 'hard',
      options: ['I apologize for the misunderstanding. Could you share more details about what you had in mind?', 'OK sorry.', 'You wrong not me.', 'I expected also not.'],
      correctAnswer: 'I apologize for the misunderstanding. Could you share more details about what you had in mind?',
      mistakeTags: ['client_response_weak'],
      banglaExplanation: 'Handling negative feedback: Apologize + ask for clarification.',
    },
  ];


  // ============ LEARNING BEHAVIOR QUESTIONS ============
  const learningBehaviorQuestions = [
    {
      questionText: 'আপনি দিনে কত মিনিট English practice করতে পারবেন?',
      questionType: 'habit', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['0–5 মিনিট', '10–15 মিনিট', '20–30 মিনিট', '45+ মিনিট'],
      correctAnswer: '45+ মিনিট',
      mistakeTags: ['practice_habit_weak', 'consistency_weak'],
      banglaExplanation: 'Daily practice time fluency journey-তে important factor.',
    },
    {
      questionText: 'আপনি আগে English course/video দেখে fluent হতে পারেননি কেন?',
      questionType: 'habit', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['Practice ছিল না', 'বুঝতাম না', 'Regular ছিলাম না', 'Teacher feedback পাইনি', 'Basic weak ছিল'],
      correctAnswer: 'Practice ছিল না',
      mistakeTags: ['practice_habit_weak', 'consistency_weak'],
      banglaExplanation: 'Past failure reason বুঝলে future plan better হয়।',
    },
    {
      questionText: 'আপনার জন্য কোন system বেশি helpful?',
      questionType: 'habit', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['শুধু video lesson', 'Teacher practice', 'Tool-based practice', 'Speaking session + feedback', 'সবগুলো একসাথে'],
      correctAnswer: 'সবগুলো একসাথে',
      mistakeTags: ['practice_habit_weak'],
      banglaExplanation: 'Learning preference বুঝে roadmap customize করা যায়।',
    },
    {
      questionText: 'English learning-এ আপনি কতদিন consistent থাকতে পারেন?',
      questionType: 'self_assessment', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['1-3 দিন', '1 সপ্তাহ', '2-4 সপ্তাহ', '1 মাস+'],
      correctAnswer: '1 মাস+',
      mistakeTags: ['consistency_weak'],
      banglaExplanation: 'Consistency fluency-র জন্য সবচেয়ে important factor.',
    },
    {
      questionText: 'আপনি কি English-এ daily কিছু পড়েন (article/social media/book)?',
      questionType: 'habit', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['না, পড়ি না', 'মাঝে মাঝে', 'সপ্তাহে ২-৩ দিন', 'প্রতিদিন'],
      correctAnswer: 'প্রতিদিন',
      mistakeTags: ['practice_habit_weak'],
      banglaExplanation: 'Daily reading input vocabulary ও grammar-এর natural exposure দেয়।',
    },

    {
      questionText: 'আপনি কি English-এ কোনো app বা tool use করে practice করেন?',
      questionType: 'habit', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['না, কোনো tool use করি না', 'আগে করতাম, এখন করি না', 'মাঝে মাঝে', 'নিয়মিত use করি'],
      correctAnswer: 'নিয়মিত use করি',
      mistakeTags: ['practice_habit_weak'],
      banglaExplanation: 'Tool-based practice structured learning indicate করে।',
    },
    {
      questionText: 'এই প্রশ্নে Option B select করুন।',
      questionType: 'attention_check', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['Option A', 'Option B', 'Option C', 'Option D'],
      correctAnswer: 'Option B',
      mistakeTags: [],
      banglaExplanation: 'Attention check question—এটি verify করে আপনি মনোযোগ দিয়ে পড়ছেন কিনা।',
    },
    {
      questionText: 'English fluent হতে কতদিন লাগে বলে মনে করেন?',
      questionType: 'self_assessment', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['7 দিন', '1 মাস', '3-6 মাস', '1 বছর+'],
      correctAnswer: '3-6 মাস',
      mistakeTags: ['practice_habit_weak'],
      banglaExplanation: 'Realistic expectation guided course-এ commitment বাড়ায়।',
    },
    {
      questionText: 'আপনি কি কোনো guided course/program follow করছেন এখন?',
      questionType: 'habit', category: 'learning_behavior', cefrLevel: 'A1', difficulty: 'easy',
      options: ['না, কিছু follow করছি না', 'YouTube video দেখি random', 'একটা course কিনেছি কিন্তু শেষ করিনি', 'হ্যাঁ, নিয়মিত follow করছি'],
      correctAnswer: 'হ্যাঁ, নিয়মিত follow করছি',
      mistakeTags: ['practice_habit_weak', 'consistency_weak'],
      banglaExplanation: 'Guided program follow করলে structured improvement হয়।',
    },
    {
      questionText: 'আপনি কি English grammar rules জানেন কিন্তু apply করতে পারেন না?',
      questionType: 'self_assessment', category: 'learning_behavior', cefrLevel: 'A2', difficulty: 'easy',
      options: ['Rules-ও জানি না', 'কিছু জানি কিন্তু apply হয় না', 'বেশিরভাগ জানি কিন্তু speaking-এ ভুল হয়', 'জানি এবং apply-ও করতে পারি'],
      correctAnswer: 'জানি এবং apply-ও করতে পারি',
      mistakeTags: ['grammar_foundation_weak', 'practice_habit_weak'],
      banglaExplanation: 'Knowledge vs Application gap বুঝতে পারলে solution targeted হয়।',
    },
  ];

  // ============ INSERT ALL QUESTIONS ============
  const allQuestions = [
    ...grammarQuestions.map(q => ({ ...q, marks: 1 })),
    ...vocabularyQuestions.map(q => ({ ...q, marks: 1 })),
    ...sentenceMakingQuestions.map(q => ({ ...q, marks: 1.5 })),
    ...listeningQuestions.map(q => ({ ...q, marks: 1 })),
    ...speakingQuestions.map(q => ({ ...q, marks: 1 })),
    ...realLifeQuestions.map(q => ({ ...q, marks: 1 })),
    ...learningBehaviorQuestions.map(q => ({ ...q, marks: 1 })),
  ];

  for (const q of allQuestions) {
    await prisma.question.create({
      data: {
        questionText: q.questionText,
        instructionText: null,
        questionType: q.questionType,
        category: q.category,
        cefrLevel: q.cefrLevel,
        difficulty: q.difficulty,
        optionsJson: JSON.stringify(q.options),
        correctAnswer: q.correctAnswer,
        explanation: null,
        banglaExplanation: q.banglaExplanation || null,
        audioUrl: (q as any).audioUrl || null,
        marks: q.marks,
        negativeMarking: 0,
        mistakeTagsJson: JSON.stringify(q.mistakeTags),
        isActive: true,
      },
    });
  }

  console.log(`Seeded ${allQuestions.length} questions`);
  console.log('Seed completed successfully!');
}

main()
  .then(async () => { await prisma.$disconnect(); })
  .catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exit(1); });
